language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t  yigityilmaz/multi-docker -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true yigityilmaz/multi-docker npm run test

after_success:
  - docker build -t yigityilmaz/multi-client ./client
  - docker build -t yigityilmaz/multi-nginx ./nginx
  - docker build -t yigityilmaz/multi-server ./server
  - docker build -t yigityilmaz/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push tYigitYilmaz/multi-client
  - docker push tYigitYilmaz/multi-nginx
  - docker push tYigitYilmaz/multi-server
  - docker push tYigitYilmaz/multi-worker
