language: generic

#sudo permissions for installing docker
sudo: required

#installing docker
services:
  - docker

#this instruction happens before installing
before_install:
  # bulding our dev dockerfile. Important to add relative path ./client
  - docker build -t yigityilmaz/multi-docker -f ./client/Dockerfile.dev ./client

  #telling travis to run our test. CI-true needed to end the test after finish it
script:
  - docker run -e CI=true yigityilmaz/multi-docker npm run test
  # this happens after all tests passed.
after_success:
  # building all production containers
  - docker build -t yigityilmaz/multi-client ./client
  - docker build -t yigityilmaz/multi-nginx ./nginx
  - docker build -t yigityilmaz/multi-server ./server
  - docker build -t yigityilmaz/multi-worker ./worker


  # log in into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # pushing all container to docker hub
  - docker push yigityilmaz/multi-client
  - docker push yigityilmaz/multi-nginx
    - docker push yigityilmaz/multi-server
  - docker push yigityilmaz/multi-worker
